### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by feross** [standard/standardx#10]
@Flet Hey! It looks like the tests have been failing for a while in this repo. Any ideas what's going on?

**Comment by Flet** [comment]
Yep!
https://github.com/standard/standardx/blob/master/test/index.js

**Comment by feross** [comment]
Ahahaha sorry I should have looked closer. (I'm just going through issues quickly trying to catch up)

**Comment by Flet** [comment]
No worries, thanks for updating them to pass. I'll try adding some basic tests this week.
