### ISSUE TITLE
The replacements should be under "standardx" property or .standardxrc file for TypeScript users

### ISSUE THREAD

**Issue by carlos-algms** [standard/standardx#13]
EsLint configurations should not be referenced on a TypeScript project. 

There is no harm, but it is contradictory.

**Comment by Flet** [comment]
Sorry I'm not quite following why this needs to be different for TypeScript projects (I have not done much TypeScript). Could you elaborate?

**Comment by carlos-algms** [comment]
TypeScript projects uses TSLint and a `tslint.json` file to customize the validations. install ESLint, or create a `eslintrc.json` file is completely unnecessary to the project itself. 

So, read the standardX config from the `package.json` or from a `standardx.json` file should be preferred. 
Like prettier or htmlhint already do.

**Comment by aMarCruz** [comment]
@carlos-algms , @Flet , "TypeScript projects uses TSLint" is somewhat rude, I think the linter is a personal choice and I have used ESLint for TS projects for more than a year with no problems.

BTW, the TS Team is also switching to ESLint.
See "Developer productivity tools and integration > Linting" in the [TypeScript Roadmap: January - June 2019](https://github.com/Microsoft/TypeScript/issues/29288).

**Comment by feross** [comment]
@carlos-algms `standard` is built on ESLint, not TSLint. Closing this issue.
