### ISSUE TITLE
[standard] Parsing error: Unexpected token = 

### ISSUE THREAD

**Issue by Junting-Liu** [standard/standardx#18]
there is my config:
```
  "standardx": { 
    "parser": "babel-eslint",
    "plugins": [ "react-hooks" ]
  }，
 "eslintConfig": {
      "rules": { 
        "react-hooks/rules-of-hooks": "error",
        "react-hooks/exhaustive-deps": "warn" 
      } 
    }
```

there is the code
`handleScroll = () => {...}`

**Comment by Junting-Liu** [comment]
I think i find the reason.
It' seem like StandardJS (the vscode plugin) can't read the standardx in package.json.
Will this problem be fixed?

**Comment by ArmorDarks** [comment]
I guess the only way to fix that would be to release Standardx VS Code extension, which will use `standardx` properties.

**Comment by ArmorDarks** [comment]
See related issue https://github.com/standard/vscode-standardjs/pull/71

This one can be closed since it's not Standardx-related,

**Comment by Junting-Liu** [comment]
> See related issue [standard/vscode-standardjs#71](https://github.com/standard/vscode-standardjs/pull/71)
> 
> This one can be closed since it's not Standardx-related,

yes, you are right.  thanks!
