### ISSUE TITLE
Package.json configs are ignored

### ISSUE THREAD

**Issue by NejcZdovc** [standard/standardx#2]
Hi,

I have one problem with standardx and `package.json` standard config.

In `package.json` (https://github.com/brave/browser-laptop/blob/master/package.json#L197) I have this values

```
"standard": {
    "global": [
      "chrome",
      "muon",
      "postMessage"
    ],
    "ignore": [
      "app/extensions/**",
      "app/browser/ads/adDivCandidates.js",
      "Brave-darwin-x64/**",
      "less/**",
      "res/**",
      "js/data/**",
      "js/lib/psl.js",
      "dist/**",
      "doc/**",
      "public/**",
      "app/ext/**",
      "app/gen/**",
      "decls/**",
      "tools/lib/rimraf.js"
    ]
  },
```

and if I use regular `standard` everything is working correctly, but if I use `standardx` this options are ignored.

Any suggestions what to do?

Thank you

**Comment by Flet** [comment]
Change the key from "standard" to "standardx" and it will work :)

```js
"standardx": {
    "global": [
      "chrome",
      "muon",
      "postMessage"
    ],
    "ignore": [
      "app/extensions/**",
      "app/browser/ads/adDivCandidates.js",
      "Brave-darwin-x64/**",
      "less/**",
      "res/**",
      "js/data/**",
      "js/lib/psl.js",
      "dist/**",
      "doc/**",
      "public/**",
      "app/ext/**",
      "app/gen/**",
      "decls/**",
      "tools/lib/rimraf.js"
    ]
  }
```

**Comment by NejcZdovc** [comment]
Thank you :smiley: 

I would suggest that this is added into `README.md` file, because now it says `All other standard features remain intact (including --fix!)` and `Running standardx with no additional configuration is the same as running standard itself.` Because of that I was assuming `package.json` should remain the same as well.

**Comment by Flet** [comment]
This is a good point!

**Comment by josephfrazier** [comment]
You could also use `standard-eject`, a tool I wrote to help migrate from `standard` to `standardx`. It changes the package.json field for you, as well as updating the `standard` references in package.json scripts.

https://github.com/josephfrazier/standard-eject

**Comment by NetOpWibby** [comment]
This information still isn't in the README.

**Comment by feross** [comment]
Fixed
