### ISSUE TITLE
Configuration for rule "react/jsx-indent" is invalid

### ISSUE THREAD

**Issue by ghost1face** [standard/standardx#24]
**What version of this package are you using?**
5.0.0

**What operating system, Node.js, and npm version?**
Windows 10
nvm
node 8.11.0
npm 6.11.2

**What happened?**
```
standardx: Unexpected linter output:

Error: BaseConfig » eslint-config-standard-jsx:
        Configuration for rule "react/jsx-indent" is invalid:
        Value [2,{"checkAttributes":true,"indentLogicalExpressions":true}] should NOT have more than 1 items.
```

**What did you expect to happen?**
StandardX to run with standard rules.  I have no custom rules in my .eslintrc, it looks that the syntax of that rule in the `eslint-config-standard-jsx` is invalid.

**Are you willing to submit a pull request to fix this bug?**
Sure, just want to make sure I'm not just doing something stupid and validate it is in fact, a bug.

**Comment by feross** [comment]
It's likely that you're using an out of date version of `eslint-plugin-react`. Can you share the output of `npm ls eslint-plugin-react`?

**Comment by feross** [comment]
I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨

**Comment by ghost1face** [comment]
You're right, I had an older version.  I upgraded and all is well now.  Thanks for pointing that out!
