### ISSUE TITLE
Can't be loaded correctly if the .eslintrc is not in the root directory

### ISSUE THREAD

**Issue by pikadun** [standard/standardx#31]
**What version of this package are you using?**
standardx@5.0.0
**What operating system, Node.js, and npm version?**
Ubuntu 20.04 LTS
Node v14.0.0
NPM 6.14.4
**What happened?**
After I moved eslintrc from the root directory to the config folder, standardx could not read the configuration correctly.
I have tried using eslintConfig to specify the configuration file in package.json, but I get an error:
```
expected object but got `"./config/.eslintrc.json"`
```
**What did you expect to happen?**
Can correctly read the configuration information in the non-root directory
**Are you willing to submit a pull request to fix this bug?**
No, I am not sure where is the problem. Maybe this is a new feature

**Comment by LinusU** [comment]
eslintrc-files applies to the folder they are in, and folder beneath them. Thus, if you place the file in a folder named `config`, the settings in that file will only apply to the files inside that folder. This is intended behaviour, if you want to change that you'll have to open an issue at the ESLint repo ☺️

**Comment by LinusU** [comment]
Responed before you edited...

`eslintConfig` in the package.json is to give eslint configuration, not to specify a path to the config file.

You can possibly set the `eslintConfiguration` to something like this:

```
"eslintConfiguration": {
  "extends": "./config/eslint.js"
}
```

and then export you eslint settings in `config/eslint.js`, not sure that it will work though...
