### ISSUE TITLE
Please update standardx to use standard v14.1.0 for ES2020 syntax

### ISSUE THREAD

**Issue by CalvinMaighan** [standard/standardx#32]
I am using ES2020 syntax, and standard v14.1.0 supports it, but this package uses standard v14.0.0

Both standard and prettier do not seem to support eslint's rule for "generator-star-spacing". Thus standardx, but I get "Parsing error: Unexpected token." hundreds of times on every line that I use the "objected?.key?.key" syntax which is basically everywhere.

**Comment by feross** [comment]
This issue is invalid. The package uses the latest standard. See: https://github.com/standard/standardx/blob/6deb2adc590942cf62c38e02b629c8c11628aa3c/package.json#L11
