### ISSUE TITLE
ignoreFields on .eslintrc.json is ignored.

### ISSUE THREAD

**Issue by Kjaer** [standard/standardx#33]
**What version of this package are you using?**
5.0.0

**What operating system, Node.js, and npm version?**
npm@6.14.4

**What happened?**
I am using external `.eslintrc.json` for eslint settings and `ignorePatterns` does not recognized by `standardx`

**What did you expect to happen?**
Looks like, `standardx` still look for `ignore` field instead of `ignorePatterns` so I am assuming that cause the problem.

**Are you willing to submit a pull request to fix this bug?**
I do.

**Comment by Kjaer** [comment]
If I use `standardx` inside `package.json`
it works fine

```json
  "standardx": {
    "ignore": [
      "/static/**/*.js"
    ]
  }
```

**Comment by Kjaer** [comment]
Any attention for this?

**Comment by feross** [comment]
This should be fixed in the latest version of `standardx` which uses ESLint 7 where I believe `ignorePatterns` was added.
