### ISSUE TITLE
Running `standardx .` exits with exit cod e0

### ISSUE THREAD

**Issue by Raynos** [standard/standardx#36]
**What version of this package are you using?** 3.0.0

**What operating system, Node.js, and npm version?** node 12

**What happened?**

I ran `standardx .` and it exited 0 even though there are lint errors in my project.

It looks the CLI does not accept folders and instead of exiting with `1` and saying folders are not supported
it says exit code 0 aka no errors.

**What did you expect to happen?**

exit code 1

**Are you willing to submit a pull request to fix this bug?** sure.

**Comment by feross** [comment]
Does the equivalent command when using `standard` have the same issue?

**Comment by Raynos** [comment]
I can confirm `standard` has the same issue.

**Comment by feross** [comment]
This issue was fixed in https://github.com/standard/standard-engine/pull/228 and released in `standard` 16 and `standardx` 7 (just released!)
